clone-target-directory=D:/clone-dirs
maven-path=D:/maven/apache-maven-3.9.8/bin
jdk-path=C:/Program Files/Java/jdk-1.8
maven-settings-xml-path=D:/maven/apache-maven-3.9.8/conf/settings.xml
sonarqube-url=http://localhost:9000
sonarqube-auth=your-sonarqube-token

# Database
spring.datasource.url=jdbc:h2:file:./data/git_repo_analyzer_data
spring.datasource.username=sa
spring.datasource.password=password
spring.h2.console.enabled=true
spring.jpa.open-in-view=false

# Hibernate configuration
spring.jpa.hibernate.ddl-auto=update